version: "3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    container_name: web
    restart: always
    depends_on:
      - db
    links:
      - "db:dbhost"
    ports:
      - "8081:80"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
      args:
        PLANET_URL: https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
        PLANET_URL_small: http://download.geofabrik.de/africa/eritrea-latest.osm.pbf
    container_name: db
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"

